#!/usr/bin/env node

//
// This executable sets up the environment and runs the HomeBridge CLI.
//

"use strict";

process.title = "homebridge";

// /usr/local/lib/node_modules/homebridge/bin/homebridge
// This line must come before importing any instrumented module.
const tracer = require('dd-trace').init({
    env:"dev"
    ,service:"homebridge-grsilver"
    ,version:"00.00.001"
    ,tags: {
        tag1:"val1"
        ,docker_service:"yes"
    }
});



// Find the HomeBridge lib
const path = require("path");
const fs = require("fs");
const lib = path.join(path.dirname(fs.realpathSync(__filename)), "../lib");

// Run HomeBridge
require(lib + '/cli')();